### ISSUE TITLE
Add ambiguous alignments to the overview report

### ISSUE THREAD

**Issue by FelixKrueger** [ewels/ngi_visualizations#1]
Hi Phil,
I'm looking to create summary reports for a large number of files. Do I understand it correctly that you 'Duplicate Alignments' is being subtracted from the total number of alignments and the remainder is being called 'Aligned Uniquely'? Maybe this category could be called 'Deduplicated Unique Alignments'?

Also, I assume that 'Did Not Align' is everything that is neither 'Duplicate Alignments' or 'Aligned Uniquely', isn't it? Would it be possible to again add the discrimination between no alignments and ambiguous alignments?

**Comment by ewels** [comment]
Ok, let's work through this. Duplicate Alignments is [fetched](https://github.com/ewels/ngi_visualizations/blob/master/stand_alone/bismark_summary/bismark_summary_report.pl#L105-L107) from the deduplication report:

``` perl
if(/^Total number duplicated alignments removed:\s+(\d+)/){
  $dup_reads = $1;
}
```

Total aligned reads are then [fetched](https://github.com/ewels/ngi_visualizations/blob/master/stand_alone/bismark_summary/bismark_summary_report.pl#L101-L104), also from the deduplication report:

``` perl
if(/^Total number of alignments analysed in .+:\s+(\d+)$/){
  $aligned_reads = $1;
}
```

Then, as you say, the unique reads are [being calculated](https://github.com/ewels/ngi_visualizations/blob/master/stand_alone/bismark_summary/bismark_summary_report.pl#L114-L116) from these two numbers:

``` perl
if($aligned_reads ne '' && $dup_reads ne ''){
  $unique_reads = $aligned_reads - $dup_reads;
}
```

..which is printed as 'Aligned Uniquely' as you say (incorrectly).

Unaligned reads are then being calculated using this value:

``` perl
my $unaligned = $total_reads - $dup_reads - $unique_reads;
```

.. also incorrectly.

So I guess, yes as you say - this is a bug, as these are actually deduplicated uniquely aligned reads.

Is the uniquely mapped read count reported anywhere else in the bismark output? How would you recommend collecting them?

Total list of current numbers we're currently trying to collect: _(broken ones struck through)_
- `$total_reads`
- `$dup_reads`
- ~~`$unique_reads`~~
- ~~`$unaligned`~~
- `$total_c`
- `$meth_cpg`
- `$unmeth_cpg`
- `$meth_cph`
- `$unmeth_cph`
- `$meth_chh`
- `$unmeth_chh`

So I guess you're suggesting that we add the following categories and fix the numbers in the broken ones above?
- `$ambig_reads`
- `$unique_dedup_reads`
- `$ambig_dedup_reads`

How do we add ambiguous alignments? Presumably `$total_reads` - _(a fixed)_  `$unique_reads`?

Apologies for basically reiterating what you said, it's been a while since I wrote this code so I'm having to remind myself of how it works. I'm not even sure how bismark handles ambiguously mapped reads to be honest?

**Comment by FelixKrueger** [comment]
Hi Phil,

Thanks for taking a look. Ambiguous reads are being discarded so there we only need to collect them once from the primary Bismark mapping report (thus, there is no $ambig_dedup_reads). For some applications it might be useful to discriminate between not mapping or not uniquely (= ambiguous) mapping reads even though neither of them makes it through to the resutls file (we currently want to know this, for 172 files...). The code for this should can probably be taken straight from the bismark2report module.

And yes if we could then correct the name to deduplicated unique reads that would be marvellous. Cheers, Felix

**Comment by ewels** [comment]
Ok, so to-do list is:
1. Collect `$ambig_reads` from the main `_bismark_bt2_PE_report.txt`
   - This line: `Sequence pairs did not map uniquely:\s+(\d+)`
2. Update report to print 'Ambiguously Aligned Reads' in graph and CSV output
3. Fix `$unaligned` to be `$total_reads - $ambig_reads - $dup_reads - $unique_reads`
   - Is there a better way to get this?
4. Rename 'Aligned Uniquely' to 'Deduplicated Unique Alignments'

Is that all correct?

**Comment by FelixKrueger** [comment]
Points 1, 2 and 4 sound fine.
To 3): 
Total reads: get from main Bismark report
Ambiguous alignments: get from main Bismark report
Unaligned reads: get from main Bismark report

Unique alignments are duplicated or not:
Duplicated (discarded) reads: get from Deduplication report
Unique dedup reads: get from Deduplication report

Does that make sense?

Something else that I found: If you want to watch 200 reports at the same time and stretch the browser window over 2 screens the graph doesn't expand but stays comparatively small in the middle. This is of course not immediately relevant.

And while we are at it: The figure legends use intense dark blue for Did not align or Unmethylated CpG, however only the dots at 100% have that colour and the main plot area is some lighter shade of darkish blue. Could this be adapted somehow?  Thanks very much.

**Comment by ewels** [comment]
ok, i'll see what I can do.

Screen width - will fix. See #2

Figure legend colour - will not fix. Please see a psychiatrist.

**Comment by ewels** [comment]
Ok, screen width fixed in ebc9b19d924eeac57bce0cc1f92e41be640514b4

Other stuff done in 628821909d998e2bd51784c176b1d641ad6b9b34 and d6387814793d1d9b4c7b40c13f63a8520a1076fb

I added both the ambiguous reads and also those that have no genomic sequence extracted - usually tiny numbers of reads, but figured that i may as well show everything.

I just tested it a little and it looked ok to me, if you could cast and eye and make sure that everything looks ok that'd be good!

**Comment by FelixKrueger** [comment]
Hi Phil, 

This looks very nice indeed! The relevant numbers are all there and the graph does now scale. The only thing that seemed to be not working any more is when you switch between CpG, CHG and CHH context the display doesn't update (it does update however if you switch between Number of Calls and Percentages though).

Great stuff, thanks!

**Comment by ewels** [comment]
Well spotted - fixed. Thanks for reporting the problems - looks better now! (And I feel more confident about the numbers!)
