### ISSUE TITLE
Trouble installing without root privilages

### ISSUE THREAD

**Issue by ManavalanG** [ewels/ngi_visualizations#4]
My attempts to install this tool have failed so far in cluster, where I don't have root privileges. Installation command at home node using `python setup.py install --user` runs without error and in my case installs them as `$HOME/.local/lib/python2.7/site-packages/ngi_visualizations-0.1-py2.7.egg`. I could do `import ngi_visualizations` successfully, but this imported library does not have any submodules such as `qualimap` under them, as verified by the output of `dir(ngi_visualizations)` - `['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']`. 

I have also tried installing with pip: `pip2 install --user .`, but this results in same problems as above (except, in addition to `.egg` file, it also installs a folder 'ngi_visualizations`). I don't need to install them as library, as I can get away with using them as standalone scripts. So, a fix is not necessary for me; I am documenting here in case someone else ran into same problem.

**Comment by ewels** [comment]
Hi @ManavalanG,

I'd strongly recommend using Conda / [Miniconda](https://conda.io/miniconda.html) to run your Python environments if possible. This is what we use and in my experience tends to make all problems like this go away (`--user` installations often don't work for me).

Note that the head fork of this repository is at https://github.com/NationalGenomicsInfrastructure/ngi_visualizations/ - this is just my development fork (though the two should be essentially the same at the moment).

We are no longer actively using or maintaining any of this code any more, since we switched to using [MultiQC](http://multiqc.info/) for our reports. Out of curiosity, which part of this package are you using?

Phil

**Comment by ManavalanG** [comment]
I'm interested in qualimap.

**Comment by ewels** [comment]
Sorry, should have figured that out from your original issue. Any reason to use this code instead of something like MultiQC?

**Comment by ManavalanG** [comment]
I was not aware of this tool. Thanks for introducing me to this. It works like a breeze. Not sure if this suggestion is a good fit here, but mentioning MultiQc in readme might help some beginners like me.

**Comment by ewels** [comment]
Ok great! Yes I wrote MultiQC sort of as a successor to several of these tools. I’d sort of forgotten about these ones to be honest. You’re right that a note in the Readme is probably a good idea..
